enableEmoji: true
noChmod: true # Don’t sync permission mode of files
noTimes: true # Don’t sync modification time of files
disableHugoGeneratorInject: true

caches:
  getJson: {dir: ':resourceDir/_cache', maxAge: 6h}
  getResource: {dir: ':resourceDir/_cache', maxAge: 6h}

security:
  funcs: {getenv: ['^HUGO_', '^GITHUB_']}

enableRobotsTXT: true
disableKinds: [RSS, taxonomy, section, term] # page, home, sitemap, robotsTXT, 404

params:
  noindex: true
  cvDownload:
    showButton: true
    downloadFileName: sv-SamoylovDN-QA-Engineer
  keywords: [SamoylovDN, cv]
  description: SamoylovDN CV

defaultContentLanguage: ru
languages:
  en:
    languageCode: en-us
    languageName: English
    title: CV - SamoylovDN QA-Engineer
    weight: 10
    params:
      cvLink: /cv.pdf
      openGraphImageName: opengraph-en.png

  ru:
    languageCode: ru-ru
    languageName: Русский
    title: Резюме - Самойлов Д.Н. (Тестировщик)
    weight: 5
    params:
      cvLink: /ru/cv.pdf
      openGraphImageName: opengraph-ru.png
