version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - administator
  - avtocod
  - Delphy
  - egrnreestroo
  - Fintech
  - ISOD
  - Kaiten
  - Laravel
  - Mikro
  - noones
  - Noones
  - paxful
  - Paxful
  - profi
  - restaurantguru
  - Surgut
  - Авиакомпания
  - авто
  - автоматизации
  - активно
  - активное
  - актуальном
  - Альфа
  - Анализ
  - анализа
  - архитектурой
  - архитектуры
  - аспекты
  - Аудит
  - аудита
  - Аэропорт
  - багрепорты
  - Багтрекер
  - базами
  - базе
  - базы
  - безопасность
  - бизнес
  - бизнеса
  - более
  - большим
  - большое
  - бота
  - брейншторминга
  - бухгалтерии
  - было
  - важных
  - Ведение
  - ведения
  - ведомственной
  - ведомственных
  - ведущих
  - взаимодействие
  - взаимодействия
  - взгляд
  - вклад
  - включала
  - включали
  - включая
  - влияющих
  - Внедрение
  - внедрении
  - внедрив
  - внедрил
  - Внедрил
  - Внёс
  - Внесение
  - внимание
  - внутри
  - возможности
  - возникающих
  - всей
  - всех
  - встряхнул
  - выкатки
  - выкаткой
  - выполнения
  - выполнял
  - высокого
  - Выявление
  - выявления
  - генерацией
  - Группа
  - группой
  - данных
  - дебаге
  - делегирование
  - дизайна
  - дизайнерами
  - добавляемых
  - документации
  - доработкой
  - Достижения
  - доходов
  - другими
  - других
  - дублирования
  - Екатеринбург
  - зависимостями
  - задач
  - задача
  - задачами
  - задачи
  - заканчивая
  - заключалась
  - занимался
  - защите
  - защиты
  - значительно
  - значительную
  - значительный
  - изменяемых
  - Инженер
  - Инструкции
  - инструменты
  - интеграции
  - интеграцию
  - интегрированные
  - интернет
  - информацией
  - информации
  - информационных
  - информацию
  - инфраструктурной
  - инцидентов
  - ИСОД
  - использование
  - использованием
  - использовании
  - использоваться
  - исправление
  - каналов
  - кандидатов
  - карты
  - качества
  - качественно
  - качественные
  - кейсы
  - клиентских
  - ключевые
  - ключевых
  - кода
  - количество
  - количеством
  - коллектив
  - коллектива
  - команде
  - команды
  - комиссий
  - компании
  - компаниях
  - компетенции
  - компонентов
  - контролем
  - контроль
  - которые
  - критические
  - Кроме
  - лекций
  - Лидер
  - линтеров
  - листам
  - листов
  - логики
  - Логирование
  - логических
  - локально
  - лучшие
  - между
  - мелкие
  - мероприятий
  - мест
  - методы
  - микросервисной
  - мобильного
  - мобильные
  - мобильных
  - модулей
  - можно
  - момент
  - мониторингом
  - монолитными
  - мотивационных
  - Навыки
  - нагрузки
  - наладить
  - наладкой
  - Налаживание
  - написанием
  - написании
  - написанные
  - направил
  - направить
  - направленных
  - напрямую
  - настройку
  - находил
  - начиная
  - непрерывной
  - несколькими
  - несложные
  - ними
  - нового
  - новые
  - нуля
  - Обеспечение
  - обеспечением
  - обеспечении
  - Обеспечивал
  - обеспечивая
  - область
  - областях
  - обмена
  - Обнаружил
  - обновленной
  - оборудования
  - обоснования
  - обучение
  - обучения
  - обязанности
  - ОМВД
  - онбординга
  - описанием
  - оптимизации
  - Оптимизировал
  - опыт
  - опыта
  - организацией
  - организации
  - организовал
  - остальное
  - отбор
  - отвечающего
  - отдел
  - отдела
  - отделами
  - откатах
  - отображающей
  - отрасли
  - отстаиванием
  - охватывало
  - ошибок
  - параллельную
  - первичной
  - перспективных
  - писал
  - планы
  - платежей
  - Платформа
  - повышение
  - повышения
  - поддержание
  - поддерживал
  - поддержке
  - поддержку
  - Поднимал
  - подразделениями
  - подразделениях
  - подходов
  - подходы
  - позволил
  - позволило
  - пользователей
  - пользовательского
  - пользу
  - последствии
  - последующее
  - Постановка
  - правки
  - практики
  - привело
  - приложение
  - приложений
  - приложения
  - приложениями
  - применении
  - Применил
  - принес
  - принимал
  - принятие
  - принятые
  - пробелы
  - проблем
  - проблемные
  - проблемы
  - проведение
  - проведением
  - проведения
  - проверки
  - Проводил
  - программирования
  - программист
  - программного
  - программных
  - продукт
  - продукта
  - продуктов
  - продукты
  - проекта
  - проектами
  - проектов
  - производил
  - процесс
  - процессах
  - процессом
  - процессы
  - пуско
  - работа
  - работоспособность
  - работу
  - работы
  - рабочих
  - разбираться
  - разбором
  - развертывании
  - развертывания
  - развитии
  - различных
  - размеры
  - разрабатываемого
  - разработал
  - Разработка
  - разработке
  - разработки
  - разработчика
  - разработчиками
  - разработчиков
  - раннего
  - распределение
  - ревью
  - регионах
  - регрессионных
  - регулярное
  - релиз
  - релизах
  - репозитория
  - репортов
  - ресторанах
  - ресторанный
  - решать
  - решений
  - решения
  - России
  - Россия
  - руководителями
  - ручное
  - самописные
  - своевременного
  - свои
  - связанных
  - связей
  - связи
  - сервиса
  - сервисов
  - сетей
  - сети
  - системе
  - системы
  - следя
  - сниффинг
  - собеседований
  - собеседования
  - согласований
  - создание
  - сопровождение
  - состоянии
  - сотрудников
  - Специализировался
  - специалистами
  - способствовал
  - стабильности
  - стали
  - стандарты
  - стилем
  - стратегии
  - стресс
  - Сургут
  - существующих
  - сформировал
  - счет
  - также
  - такие
  - текущий
  - Тест
  - тестирование
  - Тестированием
  - тестированию
  - тестирования
  - тестировщика
  - тестов
  - тестовой
  - тестовые
  - тесты
  - технологий
  - течение
  - того
  - токенизацией
  - только
  - транзакций
  - требующие
  - Тэйр
  - Тюменская
  - увеличению
  - увеличения
  - удаленно
  - удаленных
  - удовлетворенности
  - улучшение
  - улучшений
  - улучшению
  - улучшения
  - улучшить
  - Управление
  - управления
  - управлял
  - уровне
  - уровня
  - уровнях
  - условиях
  - Успешно
  - устранил
  - утверждения
  - Участвовал
  - участвовать
  - участие
  - участниками
  - фокуса
  - формализация
  - Формирование
  - функционалом
  - функциональностей
  - функциональности
  - функционирование
  - целом
  - целью
  - части
  - членами
  - чтобы
  - элементов
  - Эмуляция
  - этапах
  - эффективного
  - эффективное
  - эффективных
  - Язык
ignoreWords: []
import: []
