version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - administator
  - avtocod
  - Delphy
  - egrnreestroo
  - ISOD
  - Laravel
  - Mikro
  - noones
  - Noones
  - profi
  - restaurantguru
  - Surgut
  - Авиакомпания
  - авто
  - автоматизации
  - активно
  - актуальном
  - Альфа
  - Анализ
  - архитектурой
  - архитектуры
  - Аудит
  - Аэропорт
  - багрепорты
  - базе
  - базы
  - безопасность
  - бизнеса
  - более
  - большим
  - большое
  - брейншторминга
  - бухгалтерии
  - важных
  - Ведение
  - ведомственной
  - ведомственных
  - взаимодействие
  - включала
  - включали
  - включая
  - влияющих
  - Внедрение
  - внедрении
  - Внесение
  - возникающих
  - всей
  - всех
  - выкатки
  - выкаткой
  - выполнял
  - высокого
  - Выявление
  - выявления
  - генерацией
  - Группа
  - группой
  - дизайнерами
  - добавляемых
  - доработкой
  - Достижения
  - доходов
  - другими
  - других
  - Екатеринбург
  - зависимостями
  - задач
  - задача
  - задачами
  - задачи
  - заканчивая
  - заключалась
  - занимался
  - защите
  - защиты
  - значительную
  - изменяемых
  - Инженер
  - интегрированные
  - интернет
  - информации
  - информационных
  - инфраструктурной
  - инцидентов
  - ИСОД
  - использованием
  - использовании
  - использоваться
  - исправление
  - каналов
  - качества
  - клиентских
  - ключевых
  - кода
  - количество
  - количеством
  - команде
  - команды
  - комиссий
  - компании
  - компонентов
  - контролем
  - контроль
  - которые
  - Кроме
  - лекций
  - Лидер
  - листам
  - листов
  - логики
  - логических
  - локально
  - между
  - мелкие
  - мероприятий
  - мест
  - методы
  - микросервисной
  - мобильные
  - модулей
  - момент
  - мониторингом
  - монолитными
  - мотивационных
  - наладкой
  - написанием
  - написании
  - написанные
  - направленных
  - напрямую
  - настройку
  - находил
  - начиная
  - непрерывной
  - несколькими
  - несложные
  - нуля
  - Обеспечение
  - обеспечением
  - обеспечении
  - Обеспечивал
  - обеспечивая
  - область
  - оборудования
  - обоснования
  - обучения
  - обязанности
  - ОМВД
  - описанием
  - опыт
  - опыта
  - организацией
  - организации
  - остальное
  - отвечающего
  - отдела
  - откатах
  - отстаиванием
  - ошибок
  - параллельную
  - первичной
  - писал
  - платежей
  - повышение
  - повышения
  - поддержание
  - поддерживал
  - поддержке
  - поддержку
  - Поднимал
  - подразделениями
  - подразделениях
  - подходов
  - позволило
  - пользователей
  - пользовательского
  - пользу
  - последствии
  - правки
  - привело
  - приложений
  - приложения
  - приложениями
  - применении
  - принес
  - принимал
  - принятие
  - проблем
  - проведение
  - проведением
  - проведения
  - проверки
  - Проводил
  - программирования
  - программист
  - программного
  - программных
  - продукт
  - продукта
  - продуктов
  - продукты
  - проекта
  - проектами
  - проектов
  - производил
  - процесс
  - процессом
  - пуско
  - работа
  - работоспособность
  - работу
  - работы
  - рабочих
  - разбором
  - развертывании
  - развитии
  - различных
  - размеры
  - разрабатываемого
  - Разработка
  - разработке
  - разработки
  - разработчика
  - разработчиками
  - разработчиков
  - раннего
  - ревью
  - регионах
  - регрессионных
  - релиз
  - релизах
  - репозитория
  - репортов
  - решать
  - решений
  - решения
  - России
  - Россия
  - руководителями
  - ручное
  - самописные
  - связанных
  - связей
  - связи
  - сервиса
  - сервисов
  - сетей
  - сети
  - системы
  - следя
  - собеседования
  - согласований
  - создание
  - сопровождение
  - состоянии
  - Специализировался
  - специалистами
  - способствовал
  - стабильности
  - стали
  - стилем
  - стратегии
  - стресс
  - Сургут
  - существующих
  - счет
  - также
  - текущий
  - тестирование
  - Тестированием
  - тестированию
  - тестирования
  - тестировщика
  - тестов
  - тесты
  - технологий
  - течение
  - того
  - только
  - транзакций
  - Тэйр
  - Тюменская
  - увеличению
  - увеличения
  - удаленно
  - удаленных
  - удовлетворенности
  - улучшение
  - улучшений
  - улучшению
  - Управление
  - управлял
  - уровне
  - уровня
  - уровнях
  - условиях
  - утверждения
  - участвовать
  - участие
  - участниками
  - фокуса
  - функционалом
  - функциональностей
  - функциональности
  - функционирование
  - части
  - этапах
  - эффективное
  - эффективных
ignoreWords: []
import: []
